# Generated by Django 5.0.2 on 2024-03-02 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auction_bid_comment_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_end',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 3, 26, 24, 853642, tzinfo=datetime.timezone.utc)),
        ),
    ]
