# Generated by Django 5.0.2 on 2024-03-03 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_end',
            field=models.DateField(default=datetime.datetime(2024, 3, 10, 3, 22, 5, 700580, tzinfo=datetime.timezone.utc)),
        ),
    ]
