# Generated by Django 5.0.2 on 2024-03-03 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_auction_end_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_end',
            field=models.DateField(default=datetime.datetime(2024, 3, 10, 3, 48, 47, 840204, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
