# Generated by Django 5.0.2 on 2024-03-05 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_auction_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auction_end',
        ),
    ]
