# Generated by Django 5.0.2 on 2024-03-05 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_delete_category_remove_auction_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_winning_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
